baseURL: https://co-analysis.github.io/acses-example/
languageCode: en-gb
title: Civil Service Statistics
theme: govukhugo
publishDir: docs
canonifyurls: true
disableKinds: ["taxonomy", "term", "RSS", "sitemap"]

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2


params:
  govuk: true
  logo: crown
  product: Civil Service Statistics
  banner:
    label: "Prototype"
    message: "This is a prototype and should not be considered Official Statistics"
    url: "/about/"

menu:
  secondary:
    - identifier: about
      name: About
      pageref: about.md
      weight: 100
    - identifier: methodology
      name: Methodology
      pageref: methodology.md
      weight: 200
    - identifier: govukpub
      name: GOV.UK publication
      url: https://www.gov.uk/government/statistics/civil-service-statistics-2021
      weight: 300