---
title: "Civil Servants by NUTS3"
knit: govukhugo::govukhugo_knit
date: 2021-01-01
section: location
weight: 100
summary: "Map of civil servants by NUTS3 local authority groupings"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load packages
library(tidyverse)
library(geojsonio)
library(sp)
library(leaflet)
library(DT)
library(knitr)

# urls for downloading assets
urls <- list(
  cs19_dt = "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/820177/Statistical_tables_-_Civil_Service_Statistics_2019_-_machine_readable_headcounts_version.csv",
  nuts3_codes = "https://opendata.arcgis.com/datasets/3e1d40ce19494869b43a6997e7a539a2_0.geojson",
  nuts1_shapes = "https://opendata.arcgis.com/datasets/01fd6b2d7600446d8af768005992f76a_4.geojson",
  nuts2_shapes = "https://opendata.arcgis.com/datasets/48b6b85bb7ea43699ee85f4ecd12fd36_4.geojson",
  nuts3_shapes = "https://opendata.arcgis.com/datasets/473aefdcee19418da7e5dbfdeacf7b90_4.geojson"
)
# read in civil service stats and filter to table 15
cs19_t15 <- read_csv(urls$cs19_dt, col_types = "cccccccccccn", na = c("..", "-")) %>%
  filter(table == "t15")
# read in NUTS3 lookup codes
# rename the Western Isles to align with label is cs19
nuts3_codes <- geojson_read(urls$nuts3_codes, parse = TRUE) %>%
  pluck("features") %>%
  pluck("properties") %>%
  mutate(
    NUTS318NM = case_when(
      NUTS318CD == "UKM64" ~ "Na h-Eileanan Siar",
      TRUE ~ NUTS318NM))
# clean up cs stats table
cs_nuts3 <- cs19_t15 %>%
  filter(category_1 != "All employees", category_2 == "All employees", category_4 == "Total") %>%
  group_by(category_1) %>%
  summarise_at(vars(value), sum, na.rm = TRUE) %>%
  rename(NUTS318NM = category_1) %>%
  full_join(nuts3_codes) %>%
  mutate(pc = formattable::percent(
    value/445480),
    value = formattable::comma(value, digits = 0)) %>%
  arrange(-value)
# Read in NUTS3 shapes
nuts3_spdf <- geojson_read(urls$nuts3_shapes, what = "sp")
# Read in NUTS1 shapes, select only London
nuts1_spdf <- geojson_read(urls$nuts1_shapes, what = "sp")
london_spdf <- nuts1_spdf[nuts1_spdf$nuts118cd == "UKI",]
# Read in NUTS2 shapes, select Greater Manchester
nuts2_spdf <- geojson_read(urls$nuts2_shapes, what = "sp")
manchester_spdf <- nuts2_spdf[nuts2_spdf$nuts218cd == "UKD3",]
# Select remaining Core Cities from NUTS3
core_cities <- c(Birmingham = "UKG31", Bristol = "UKK11", Cardiff = "UKL22", 
                 Glasgow = "UKM82", Leeds = "UKE42", Liverpool = "UKD72", 
                 Newcastle = "UKC22", Nottingham = "UKF14", Sheffield = "UKE32")
cities_spdf <- nuts3_spdf[nuts3_spdf$nuts318cd %in% core_cities,]

wm_data <- cs_nuts3 %>%
  filter(NUTS318CD == "UKI32")
wm_spdf <- sp::merge(nuts3_spdf, wm_data, by.x = "nuts318cd", by.y = "NUTS318CD")

other_areas <- cs_nuts3 %>%
  filter(NUTS318CD != "UKI32")

# merge nuts3 shapes with data
leaf_dt <- sp::merge(nuts3_spdf, cs_nuts3, by.x = "nuts318cd", by.y = "NUTS318CD")
# create colouring function
bincol <- colorBin(palette = "YlGnBu",
                   domain = leaf_dt$value,
                   bins = c(0, 500, 1000, 2500, 5000, 7000, 50000),
                   pretty = FALSE,
                   na.color = "#eeeeee")


```


As of 31 March 2019, there were 445,480 civil servants working for the UK Civil Service &mdash; of which 20% work in London. The map shows the number of UK civil servants by the local area (NUTS3 areas) of their main work location. There are also a further 7,920 civil servants who work overseas or whose working location is not known.

:::{.govuk-grid-row .data-card}
:::{.govuk-grid-column-full}

```{r map, echo=FALSE, warning=FALSE}
leaflet(leaf_dt, width = "100%", height = 600) %>%
  addProviderTiles(provider = providers$CartoDB.PositronNoLabels) %>%
  # addTiles(
  #   urlTemplate = "https://api.os.uk/maps/raster/v1/zxy/Light_3857/{z}/{x}/{y}.png?key=enjDvKSofsrqOUmqo3jUcxEsdMjI9yk4",
  #   attribution = "Contains OS data © Crown Copyright and database rights 2022",
  #   options = tileOptions(
  #     minZoom = 5,
  #     maxZoom = 16
  #   )
  # ) %>%
  addMapPane("overlay", zIndex = 600) %>%
  addMapPane("labels", zIndex = 900) %>%
  addProviderTiles(providers$CartoDB.PositronOnlyLabels,
                   options = providerTileOptions(pane = "labels")) %>%
  addPolygons(color = "#aaaaaa",
              weight = 1,
              fillColor = ~bincol(value),
              popup = ~paste(NUTS318NM, value, sep = ": "),
              fillOpacity = 0.5) %>%
  addPolygons(data = london_spdf,
              color = "#F47738",
              opacity = 1,
              weight = 2,
              fill = FALSE,
              group = "London",
              options = pathOptions(pane = "overlay")) %>%
  addPolygons(data = manchester_spdf,
              color = "#F47738",
              opacity = 1,
              weight = 3,
              fill = FALSE,
              group = "Core Cities",
              options = pathOptions(pane = "overlay")) %>%
  addPolygons(data = cities_spdf,
              color = "#F47738",
              opacity = 1,
              weight = 3,
              fill = FALSE,
              group = "Core Cities",
              options = pathOptions(pane = "overlay")) %>%
  addLegend(position = "topright", pal = bincol, values = ~leaf_dt$value, 
            title = "Headcount", opacity = 0.8) %>%
  addLayersControl(
    overlayGroups = c("London", "Core Cities"), position = "bottomright",
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  hideGroup(c("London", "Core Cities"))
```

:::

:::
